---
# Configuration for release-drafter.
# See: https://github.com/release-drafter/release-drafter
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "release-major"
  minor:
    labels:
      - "release-minor"
  patch:
    labels:
      - "release-patch"
  default: patch
categories:
  - title: "Breaking changes"
    labels:
      - "release-major"
  - title: "Features"
    labels:
      - "release-minor"
      - "enhancement"
  - title: "Bug fixes"
    labels:
      - "bug"
      - "release-patch"
  - title: "Maintenance"
    labels:
      - "documentation"
      - "dependencies"
      - "maintenance"
      - "refactor"
change-template: "- $TITLE (@$AUTHOR via #$NUMBER)"
exclude-labels:
  - "skip-release-notes"
template: |
  ## Changes

  $CHANGES
