version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      # Avoid a bug with virtualenv and pip
      # Reference: https://github.com/python-poetry/poetry/issues/10056
      - pip install "virtualenv<20.28.1" -U
    post_checkout:
      # Full history is required for dunamai to calculate the version
      - git fetch --unshallow || true
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # (https://python-poetry.org/docs/managing-dependencies/#dependency-groups)
      # and leverage READTHEDOCS_VIRTUALENV_PATH for environment.
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with dev,docs --all-extras

sphinx:
  builder: html
  configuration: docs/conf.py
