version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # Full history is required for dunamai to calculate the version
    - git fetch --unshallow || true
    # Install poetry
    # https://python-poetry.org/docs/#installing-manually
    - pip install poetry
    # Install poetry-dynamic-versioning plugin
    - poetry self add "poetry-dynamic-versioning[plugin]"
    # Build the project
    - poetry build --format sdist
    # Extract the built sdist
    - mkdir -p dist/sdist && tar -xzf dist/*.tar.gz -C dist/sdist/
    # Replace the files from the repo with the built sdist
    - mv dist/sdist/*/pyproject.toml .
    # Tell poetry to not use a virtual environment
    - poetry config virtualenvs.create false
    # Install dependencies with 'docs' dependency group
    # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
    - poetry install --with dev,docs --all-extras
    # Build the docs
    - poetry run mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml

mkdocs:
  configuration: mkdocs.yml
