# This workflow will install Python dependencies, run tests and black with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      # This is needed to avoid a warning from SQLAlchemy
      # https://sqlalche.me/e/b8d9
      # We can remove this once we upgrade to SQLAlchemy >= 2.0
      SQLALCHEMY_SILENCE_UBER_WARNING: "1"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .[collate,cell_locations,dev]
      - name: Test with pytest
        run: |
          pytest
